import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { StoreProvider } from "./provider";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { dir } from 'i18next'



const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,

}: Readonly<{
  children: React.ReactNode;
  params: {
    lng: string;
  };
}>) {
  const { lng } = await params

  return (
    <StoreProvider>
      <html lang={lng} dir={dir(lng)} >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
